version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - app-network
    extra_hosts:
      - "vector:127.0.0.1"
    environment:
      DOCKER_HOST: tcp://docker-dind:2375
      DOCKER: '{"host": "tcp://docker-dind:2375"}'
    command: sh -c "sleep 60 && npm install && npx tsc && node ./dist/index.js"
    depends_on:
      - docker-dind  # Зависит от контейнера с Docker

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    user: root
    volumes:
      - .:/var/www/html
    environment:
      HOST_DIR: "/home/egor/gitlab/accel_docker"  # Для работы тестирования, менять на расположение откуда запускается Docker
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./for_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - node

  psql:
    build:
      context: .
      dockerfile: Dockerfile.psql
    ports:
      - "5432:5432"
    networks:
      - app-network

  docker-dind:
    image: docker:dind  # Используем Docker-in-Docker 
    privileged: true  # Необходимо для работы DinD
    volumes:
      - docker-data:/var/lib/docker  # Сохраняем данные Docker внутри контейнера
    networks:
      - app-network
    environment:
      DOCKER_TLS_CERTDIR: ""  # Отключаем TLS
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]

networks:
  app-network:
    driver: bridge

volumes:
  docker-data:  # Том для хранения данных Docker
