version: '3.9'

services:
  node:
    container_name: accel-node
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 3055:3000
    volumes:
      - .:/app
    networks:
      - app-network
    extra_hosts:
      - "vector:127.0.0.1"
    environment:
      DOCKER_HOST: tcp://docker-dind:2375
      DOCKER: '{"host": "tcp://docker-dind:2375"}'
    command: sh -c "sleep 30 && cd ./accelerator && npm install && cd ../nitori_base && npm install && npx tsc && node ./dist/index.js"
    depends_on:
      - docker-dind 

  php:
    container_name: accel-php
    build:
      context: .
      dockerfile: Dockerfile.php
    user: root
    volumes:
      - ./accelerator:/var/www/html
      - ./backups:/backups
      - .env:/.env
    environment:
      HOST_DIR: "/var/www/html"  
      DOCKER_HOST: tcp://docker-dind:2375
      DOCKER: '{"host": "tcp://docker-dind:2375"}'    
    networks:
      - app-network

  nginx:
    container_name: accel-nginx
    image: nginx:1.24.0
    ports:
      - "8080:80"
    volumes:
      - ./accelerator:/var/www/html
      - ./for_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./for_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - node

  psql:
    container_name: accel-psql
    build:
      context: .
      dockerfile: Dockerfile.psql
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./backups:/backups
      - .env:/.env
    ports:
      - "5050:${POSTGRES_INNER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 15s
      retries: 5
    networks:
      - app-network
    restart: always

  docker-dind:
    container_name: accel-docker-bind
    image: docker:dind 
    privileged: true  
    volumes:
      - docker-data:/var/lib/docker  
      - ./accelerator:/var/www/html
    networks:
      - app-network
    environment:
      DOCKER_TLS_CERTDIR: ""
      TIMEOUT: 60  
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]

networks:
  app-network:
    driver: bridge

volumes:
  docker-data:
