FROM node:18

RUN apt-get update && apt-get install -y \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируем ВЕСЬ исходный код
# COPY . .

# COPY for_accelerator/package.json ./accelerator/

# Устанавливаем зависимости
# RUN cd ./accelerator && npm install 
# RUN cd ./nitori_base && npm install

# Компилируем TypeScript
# RUN cd ./nitori_base && npx tsc

EXPOSE 3000

# WORKDIR /app/nitori_base

# Указываем точку входа
# CMD ["node", "./dist/index.js"]
