FROM node:18

RUN apt-get update && apt-get install -y \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# run apt-get install -y docker-ce-cli

# COPY package*.json ./

# RUN npm install

# COPY . .

# RUN npx tsc

EXPOSE 3000

# CMD ["node", "./dist/index.js"]
